yml file problems

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,61 +1,52 @@
-name: CI
-
 on:
   pull_request:
-
-
+  
 jobs:
-  run-tests:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-latest]
-        python-version:
-          - "3.9"
-
-    name: Test
-    runs-on: ${{matrix.os}}
+  test:
+    name: python test
+    runs-on : ubuntu-latest
     env:
       log_Output: README.md
-
+      temp_log: temp_log.txt
     steps:
-
       - name: Checkout repository
         uses: actions/checkout@v3
-
-      - name: Set up python
-        uses: actions/setup-python@v4
-        with:
-          python-version: ${{matrix.python-version}}
-    
-
+        
       - name: Install pytest
         run: pip install -U pytest
 
-      - name: Run pytest
-        run: pytest > temp_log.txt
 
+      # runs the test and puts the output in a temporary file that will not be tracked by git
+      - name: Run pytest
+        run : pytest -q > $temp_log
+
+      # add failure badge if the test failed
       - name: add test fail badge
-        if: failure()
-        run: echo -e "\n## __results from $(date +'%Y-%m-%d')__ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} ![Static Badge](https://img.shields.io/badge/test-fail-red)\n" >> $log_Output
+        if  : failure()
+        run : echo -e "\n## __results from $(date +'%Y-%m-%d')__ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} ![Static Badge](https://img.shields.io/badge/test-fail-red)\n" >> $log_Output
+
+      # add pass badge if the test didn't fail
+      - name: add test pass badge
+        if  : success()
+        run : echo -e "\n## __results from $(date +'%Y-%m-%d')__ ${{ github.event.pull_request.head.ref }} -> ${{ github.event.pull_request.base.ref }} ![Static Badge](https://img.shields.io/badge/test-pass-green)\n" >> $log_Output
 
       - name: config git
-        if: success() || failure()
-        run: |
+        if  : success() || failure()
+        run : |
           git config --global user.email "action@github.com"
           git config --global user.name "GitHub Actions"
 
+      #the output log will be appended to the README.md in master so a checkout first is needed
       - name: checkout main
         if  : success() || failure()
         run : |
           git fetch
           git checkout main
 
+
       - name: append log to README
         if  : success() || failure()
-        
         run : cat $temp_log >> $log_Output
-
 
       - name: commit logs
         if  : success() || failure()
@@ -65,4 +56,3 @@ jobs:
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
